//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DiskfltInst.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDR_DRVX86                      202
#define IDR_DRVX64                      203
#define IDD_GETPASS                     204
#define IDD_LOGIN                       205
#define IDD_ADVSET                      208
#define IDD_ADDTHAWSPACE                210
#define IDD_MOUNTMANAGE                 211
#define IDD_ADDMOUNT                    212
#define IDD_SAVEDATAMANAGE              213
#define IDD_ADDSAVEDATA                 214
#define IDS_QUESTION                    218
#define IDS_INFORMATION                 219
#define IDS_ERROR                       220
#define IDS_WARNING                     221
#define IDS_DRIVE_LETTER                222
#define IDS_PARTITION_TYPE              223
#define IDS_TOTAL_CAPACITY_MB           224
#define IDS_USED_CAPACITY_MB            225
#define IDS_STATUS                      226
#define IDS_COMMAND                     227
#define IDS_PROTECT                     228
#define IDS_UNPROTECT                   229
#define IDS_NO_COMMAND                  230
#define IDS_UNINSTALL_DRIVER            231
#define IDS_UNINSTALL_ERROR_PROTECTED   232
#define IDS_UNINSTALL_CONFIRM           233
#define IDS_UNINSTALL_CONFIRM_CONFIG    234
#define IDS_OPERATION_SUCCESS_REBOOT    235
#define IDS_OPERATION_SUCCESS_ASK_REBOOT 236
#define IDS_OPERATION_FAILED_ERROR_CODE 237
#define IDS_CONFIRM_READ_CONFIG         238
#define IDS_NOTICE_MEMORY_NEEDED        239
#define IDS_ORIG_PASSWORD_WRONG         240
#define IDS_CONFIG_UNCHANGED            241
#define IDS_WHITELIST_SYS_UNPROTECTED   242
#define IDS_MEMORY_TOO_LOW              243
#define IDS_NEW_VERSION_SYS_PROTECTED   244
#define IDS_NEW_VERSION_ASK_DOWNLOAD    245
#define IDS_NO_UPDATE_AVAILABLE         246
#define IDS_MULTIPLE_INSTANCE           247
#define IDS_PASSWORD_WRONG              248
#define IDS_CONFIRM_PASSWORD_WRONG      249
#define IDS_VISIBILITY                  250
#define IDS_SIZE                        251
#define IDS_FILENAME                    252
#define IDS_CHECKSUM                    253
#define IDS_INVISIBLE                   254
#define IDS_VISIBLE                     255
#define IDS_DRIVER_COUNT_EXCEEDED       256
#define IDS_CALC_CHECKSUM_FAILED        257
#define IDS_CHECKSUM_EXISTS             258
#define IDS_DRIVER_FILES                259
#define IDS_ALL_FILES                   260
#define IDS_THAWSPACE_COUNT_EXCEEDED    261
#define IDS_THAWSPACE_DRIVE_LETTER_EXISTS 262
#define IDS_THAWSPACE_DRIVE_LETTER_EMPTY 263
#define IDS_THAWSPACE_MAIN_DRIVE_EMPTY  264
#define IDS_THAWSPACE_SIZE_ZERO         265
#define IDS_OPEN_FILE_FAILED            266
#define IDS_READ_SIZE_FAILED            267
#define IDS_THAWSPACE_FILE              268
#define IDS_PARTITION                   269
#define IDS_READONLY                    270
#define IDS_YES                         271
#define IDS_NO                          272
#define IDS_MOUNT_COUNT_EXCEEDED        273
#define IDS_MOUNT_PARTITION_EXISTS      274
#define IDS_LOCK_VOLUME_FAILED          275
#define IDS_UNMOUNT_VOLUME_FAILED       276
#define IDS_SAVEDATA_COUNT_EXCEEDED     277
#define IDS_VOLUME_CANNOT_SAVEDATA      278
#define IDS_MOUNT_DRIVE_LETTER_EMPTY    279
#define IDS_MOUNT_PARTITION_EMPTY       280
#define IDS_SAVEDATA_PARTITION_EMPTY    281
#define IDC_VOLUMELIST                  1000
#define IDC_INSTALLSYS                  1001
#define IDC_APPLY                       1002
#define IDC_COMMAND                     1003
#define IDC_MODIFYPWD                   1004
#define IDC_CURRENT_PWD                 1005
#define IDC_EXIT                        1005
#define IDC_NEW_PWD                     1008
#define IDC_PASSWORD                    1008
#define IDC_CONFIRM_PWD                 1009
#define IDC_PROTECTSYS                  1011
#define IDC_VER                         1013
#define IDC_ENABLE_PROTECT              1014
#define IDC_ADVANCEDSETTING             1015
#define IDC_ENABLE_THAWSPACE            1016
#define IDC_CHECKUPDATE                 1017
#define IDC_DRIVER_WHITELIST            1018
#define IDC_DRIVER_BLACKLIST            1019
#define IDC_DRIVER_DENY                 1020
#define IDC_DRIVER_LIST                 1022
#define IDC_THAWSPACE_LIST              1023
#define IDC_DRIVER_DELSEL               1024
#define IDC_DRIVER_ADD                  1025
#define IDC_THAWSPACE_ADD               1026
#define IDC_THAWSPACE_DEL               1027
#define IDC_ADDNEW                      1030
#define IDC_VOLLETTER                   1031
#define IDC_FILESIZE                    1032
#define IDC_PARTITION                   1032
#define IDC_USEEXISTING                 1033
#define IDC_FILEPATH                    1034
#define IDC_BROWSE                      1035
#define IDC_HIDE                        1036
#define IDC_CREATENEW_MAINDRIVE         1037
#define IDC_MOUNT_MANAGE                1037
#define IDC_MOUNT_LIST                  1038
#define IDC_ADD_MOUNT                   1039
#define IDC_DELETE_MOUNT                1040
#define IDC_REFRESH_LIST                1041
#define IDC_READONLY                    1042
#define IDC_ALLOWMOUNT                  1050
#define IDC_PARTITION_SELECTALL         1050
#define IDC_THAWSPACE_SELECTALL         1051
#define IDC_THAWSPACE_UNHIDE            1052
#define IDC_THAWSPACE_HIDE              1053
#define IDC_SAVEDATA_MANAGE             1057
#define IDC_ADD_SAVEDATA                1058
#define IDC_DELETE_SAVEDATA             1059
#define IDC_SAVEDATA_LIST               1060

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1061
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
